"""locker, client and trainer models

Revision ID: 76237fb034a0
Revises: c3f7cf1ea367
Create Date: 2025-12-23 17:36:59.999023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76237fb034a0'
down_revision: Union[str, Sequence[str], None] = 'c3f7cf1ea367'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
